import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import authRoutes from './routes/authRoutes.js';
import userRoutes from './routes/userRoutes.js';
import ownerRoutes from './routes/ownerRoutes.js';
import adminRoutes from './routes/adminRoutes.js';
import reviewRoutes from './routes/reviewRoutes.js';
import notificationRoutes from './routes/notificationRoutes.js';
import { errorHandler } from './middleware/error.js';
import rateLimit from 'express-rate-limit';
import crypto from 'crypto';

const app = express();
const origin = process.env.FRONTEND_URL || 'http://localhost:3000';
app.use(cors({ origin, credentials: true }));
app.use(express.json());
app.use((req, res, next) => { req['requestId'] = crypto.randomUUID(); next(); });
app.use(morgan('dev'));
const authLimiter = rateLimit({ windowMs: 60_000, max: 30 });
const writeLimiter = rateLimit({ windowMs: 60_000, max: 120 });
app.get('/api/health', (req, res) => res.json({ ok: true }));
app.use('/api/auth', authLimiter, authRoutes);
app.use('/api', userRoutes);
app.use('/api', writeLimiter, ownerRoutes);
app.use('/api', adminRoutes);
app.use('/api', reviewRoutes);
app.use('/api', notificationRoutes);
app.use(errorHandler);
export default app;
